account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('', views.login, name="login"),
    path('register<str:role>/', views.register, name="register"),
    path('delete/<str:pk>/', views.delete_user, name="delete-user"),
    path('update_password/<str:pk>/', views.update_password, name='update_password'),
    path('update_password_forgot/<str:pk>/', views.update_password_forgot, name='update_password_forgot'),
    path('update_account/', views.update_account, name='update_account'),
    path('forgot_password/', views.forgot_password, name="revoke-new-password"),
    path('logout/', views.logout, name="logout")
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name="index"),
    path('register<str:role>/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="log-out"),
    path('admin-dashboard/', views.admin, name="admin-dashboard"),
]

post/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include("post_app.urls")),
    path('account/', include("account.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from .forms import *
from .inc import *
from django.contrib import messages


def logout(request):
    request.session.pop("user-role", 0)
    request.session.pop("email", 0)
    return redirect('main:login')


def index(request):
    context = {"nav": navbar_tool(request)}
    return render(request, 'main/index.html', context)


def register(request, role="customer"):
    print(dict(request.session))
    if request.method == "POST":
        rf = RegisterForm(request.POST)
        if rf.is_valid():
            if not User.objects.filter(email=request.POST.get("email")).exists():
                gs = rf.save(commit=False)
                if role == "admin":
                    gs.is_admin = True
                elif role == "counter":
                    gs.is_counter = True
                elif role == "postman":
                    gs.is_postman = True
                else:
                    gs.is_costumer = True
                gs.save()
                if role == "costumer" and request.session.get("admin") is None:
                    messages.info(request, "Please login to proceed.")
                    return redirect("main:login")
                return redirect("main:index")
            else:
                messages.warning(request, "User Email is already taken.")
                return redirect(reverse('main:register', args=[role]))
    rf = RegisterForm()
    return render(request, 'main/register.html', {"form": rf, "nav": navbar_tool(request)})


def login(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(email=email, password=password).exists():
            user = User.objects.get(email=email, password=password)
            flag = ""
            if user.is_admin:
                flag = "admin"
            elif user.is_counter:
                flag = "counter"
            elif user.is_postman:
                flag = "postman"
            else:
                flag = "costumer"
            request.session["user-role"] = flag
            request.session["email"] = user.email
            if flag == "admin":
                return redirect('main:admin-dashboard')
            return render(request, 'main/index.html', {"nav": navbar_tool(request)})
        else:
            messages.warning(request, "User doesn't exist!, with this credentials.")
    return render(request, 'main/login.html', {"nav": navbar_tool(request)})


def admin(request):
    users = None
    role = request.GET.get("role")
    if role == "admin":
        users = User.objects.filter(is_admin=True)
    elif role == "postman":
        users = User.objects.filter(is_postman=True)
    elif role == "costumer":
        users = User.objects.filter(is_costumer=True)
    else:
        users = User.objects.all()
    return render(request, "main/admin.html", {"users": users, "nav": navbar_tool(request)})

templates/main/admin.html
{% extends 'main/base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block navbar %}
    {% include 'main/navbar.html' %}
{% endblock %}

{% block middle %}
    <div class="card m-1">
    <h5 class="card-title">Select User Type</h5>
        <div class="card-body">
            <a href="{% url 'account:admin-dashboard' %}?role=admin" class="btn btn-info btn-sm">Admin</a>
            <a href="{% url 'account:admin-dashboard' %}?role=costumer" class="btn btn-secondary btn-sm">Costumer</a>
            <a href="{% url 'account:admin-dashboard' %}?role=postman" class="btn btn-success btn-sm">Postman</a>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col"># Id</th>
                  <th scope="col">First name</th>
                  <th scope="col">Last name</th>
                  <th scope="col">email</th>
                  <th scope="col">Phone</th>
                  <th scope="col">Address</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              {% for user in users %}
                <tr>
                  <th scope="row"> {{ user.id }} </th>
                  <td>{{ user.first_name }}</td>
                  <td>{{ user.last_name }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.phone }}</td>
                  <td>{{ user.address }}</td>
                  <td><a href="#" class="btn btn-danger btn-sm">Delete</a></td>
                  <td><a href="#" class="btn btn-primary btn-sm">Update</a></td>
                </tr>
              {% empty %}
                  <h3>No user exists.</h3>
              {% endfor %}
              </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ethiopian Postal Service | {% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'  %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'  %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css'  %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css'  %}">
    <script type="text/javascript" src="{% static 'js/jquery.js'  %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'  %}"></script>
</head>
<body>
<div class="container">
    <!-- Start of top header image -->
    <section class="top-header-img">
        <img src="{% static 'image/top-header.gif'%}">
    </section>

    <!-- End of top header image -->
    <!-- Start of Navigation bar -->
    {% block navbar %}
    {% endblock %}
    <!-- End of Navigation bar -->

    <section class="middle mt-5">
        {% block middle %}
        {% endblock %}
    </section>
    <section class="footer-2">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-sm-4 col-xs-12">
                        <div class="single_footer">
                            <h4>Address</h4>
                            <address>
                                <ul>
                                    <li><a href="#">Ethiopian Postal Service</a></li>
                                    <li><a href="#">Addis Ababa</a></li>
                                    <li><a href="#">Ethiopian</a></li>
                                    <li><a href="#"><i class="fa fa-phone pright-10"></i> +251-923-750695</a></li>
                                    <li><a href="#"><i class="fa fa-envelope pright-10"></i> Ethiopostalsystem.com</a>
                                    </li>
                                </ul>
                            </address>
                        </div>
                    </div><!--- END COL -->
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="single_footer single_footer_address">
                            <h4>Map Location</h4>
                            <div class="mapouter">
                                <div class="gmap_canvas">
                                    <iframe width="420" height="213" id="gmap_canvas"
                                            src="https://maps.google.com/maps?q=2Q39+C5P,%20Addis%20Ababa&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                            frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                                    <a href="https://putlocker-is.org"></a><br>
                                    <style>.mapouter {
                                        position: relative;
                                        text-align: right;
                                        height: 213px;
                                        width: 345px;
                                    }</style>
                                    <a href="https://www.embedgooglemap.net">how to add google maps to a website</a>
                                    <style>.gmap_canvas {
                                        overflow: hidden;
                                        background: none !important;
                                        height: 213px;
                                        width: 345px;
                                    }</style>
                                </div>
                            </div>
                        </div>
                    </div><!--- END COL -->
                    <div class="col-md-4 col-sm-4 col-xs-12 mr-sm-2">
                        <div class="social_profile">
                            <ul>
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div><!--- END COL -->
            </div><!--- END ROW -->
        </div><!--- END CONTAINER -->
    </section>
    <section class="footer-1">
        <div class="card">
            <div class="card-body bg-success">
                <p class="text-center text-dark mt-3">Copyright &copy; 2014 Online Ethiopian Postal System. </br> All
                    rights
                    reserved.</p>
            </div>
        </div>
    </section>
</div>
</body>
</html>

templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
    index page
{% endblock %}

{% block navbar %}
    {% include "main/navbar.html" %}
{% endblock %}

{% block middle %}
    <h2>Wel-Come to EPMS</h2>
    <p class="card">
        <p class="card-body align-content-center">
            This Page all clients see before they log into the system.
            <br>we will update it very soon.
        </p>
    </p>
{% endblock %}

templates/main/login.html
{% extends 'main/base.html' %}
{% block title %}
    Login
{% endblock %}

{% block navbar %}
    {% include 'main/navbar.html' %}
{% endblock %}

{% block middle %}
<form class="form-signin text-center" action="" method="post">
    {% csrf_token %}
    <img class="mb-4" src="../../static/image/mk.jpg" alt="" width="100" height="100">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <div style="color: red;font-family: monospace;font-size: 19px">
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}

        {% endif %}
    </div>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block  ml-3" name="login" type="submit">Login</button>
</form>
{% endblock %}

templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if nav.status == "admin" %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:admin-dashboard' %}">Users</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Manage Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'account:register' 'admin'%}">Register Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:register' 'counter'%}">Register counter</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:register' 'postman' %}">Register Post-man</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:register' 'costumer'%}">Register Costumer</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
            {% elif nav.status == "costumer" %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Sent Post</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Notification</a>
            </li>
            {% endif%}

        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if nav.status %}
                <a class="btn btn-outline-warning my-2 my-sm- " href="{% url 'account:log-out' %}" >Logout({{ nav.name }})</a>
            {% else %}
                <a class="btn btn-outline-success my-2 my-sm-0 ml-3" href="{% url 'account:login' %}">Login</a>
                <a class="btn btn-outline-success my-2 my-sm-0 ml-3" title="for costumer registration only." href="{% url 'account:register' 'costumer' %}">Register</a>
            {% endif %}
        </form>
    </div>
</nav>

templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block navbar %}
    {% block comment %}

    {% endblock %}

{% endblock %}

{% block middle %}
    <form class="form-signin text-center" style="max-width: 500px!important;" action="" method="post">
        <img class="mb-4" src="../../static/image/mk.jpg" alt="" width="100" height="100">
        <h1 class="h3 mb-3 font-weight-normal">Please register here</h1>

        {% csrf_token %}
        {% for foo in form %}
            {{ foo.label }}{{ foo.id_for_label  }}{{ foo  }}
        {% endfor %}

        <button class="btn btn-lg btn-primary btn-block ml-3" type="submit">Sign-Up</button>
    </form>
{% endblock %}

templates/main/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>
<body>

<a href="#" onclick="kimash()" class="btn btn-sm btn-success m-3">Kimash</a>
<div class="m-5">
    <div id="area">
        <input type="text" minlength="4">
    </div>
</div>

<script>
    function kimash(){
        let ar = document.getElementById('area')
        let link = window.location.search
        let obj = {}
        let key = ''
        let value = ''
        let turnk = true
        for (let i = 1; i < link.length; i++) {
            if(link[i]==="="){
                turnk = false
                continue
            }else if(link[i]==="&"){
                obj[key]=value
                key = ""
                value = ""
                turnk = true
                continue
            }
            if (turnk)
                key+=link[i]
            else
                value+=link[i]
        }
        obj[key]=value
    }
</script>

{#        -----------------------------               #}
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>