account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('', views.login, name="login"),
    path('register<str:role>/', views.register, name="register"),
    path('delete/<str:pk>/', views.delete_user, name="delete-user"),
    path('update_password/<str:pk>/', views.update_password, name='update_password'),
    path('update_password_forgot/<str:pk>/', views.update_password_forgot, name='update_password_forgot'),
    path('update_account/', views.update_account, name='update_account'),
    path('forgot_password/', views.forgot_password, name="revoke-new-password"),
    path('logout/', views.logout, name="logout")
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name="index"),
    path('register<str:role>/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="log-out"),
    path('admin-dashboard/', views.admin, name="admin-dashboard"),
]

post/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include("post_app.urls")),
    path('account/', include("account.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_app/urls.py
from django.urls import include, path
from .views import *

app_name = "post"
urlpatterns = [
    path("", index, name="index-view"),
    path("test/", test, name="test-page"),
    path("admin/", admin_dashboard, name="admin-dashboard"),
    path("user/", user_dashboard, name="user-dashboard"),
    path("counter/", counter_dashboard, name="counter-dashboard"),
    path("postman/", postman_dashboard, name="postman-dashboard"),
    path("manager/", manager_dashboard, name="manager-dashboard"),
    path("seen/<str:pk>/", all_to_seen, name="all-or-one-to-seen")
]

templates/post/index.html
{% extends 'post/index_base.html' %}

{% block title %}
    Index
{% endblock %}

{% block breadcrumb %}
    index
{% endblock %}

{% block middle %}
    {% load static %}
    <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">From our memorial gallery</h5>
                        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-indicators">
                                {% for carousel in carousels %}
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}"
                                        class="{% if forloop.first %} active {% endif %}" aria-current="true" aria-label="{{ forloop.counter }}"></button>
                                {% endfor %}
                            </div>

                            <div class="carousel-inner">
                                {% for carousel in carousels %}
                                <div class="carousel-item {% if forloop.first %} active {% endif %} ">
                                    <img src="{{ carousel.photo.url }}" class="d-block w-100" alt="Image doesn't exist.">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>{{ carousel.title }}</h5>
                                        <p>{{ carousel.caption }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>

                            <button class="carousel-control-prev" type="button"
                                    data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button"
                                    data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>

                        </div><!-- End Slides with captions -->

                    </div>
                </div>
            </div>
        </div>
    <div class="row justify-content-center">
            <div class="col-lg-9">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Wel come Guest</h5>
                        <p>
                            Ethiopian Online Postal System is dedicated to serve its people to connect around the word
                            throug postal comminication method.
                        </p>
                        <h5 class="card-title">To send Post You have To follow some step.</h5>
                        <ol class="list-group list-group-numbered pl-4">
                            <li class="list-group-item">Register</li>
                            <li class="list-group-item">something</li>
                            <li class="list-group-item">something</li>
                            <li class="list-group-item">something</li>
                            <li class="list-group-item">something</li>
                        </ol>
                        <p class="mt-4">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </p>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/post/index_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}| Online Ethiopian Post Office</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/post.jpg' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body class="toggle-sidebar" onload="post_none()">
<div class="page-wrapper ">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS or message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="custom-modal">
                <div class="succes succes-animation icon-top"><i class="bi bi-check2"></i></div>

                <div class="content">
                    <p class="message-type text-center small text-success">{{ message }}</p>
                </div>
            </div>
            {% else %}
            <div class="custom-modal">
                <div class="danger danger-animation icon-top"><i class="bi bi-x-lg"></i></div>
                <div class="content">
                    <p class="message-type text-danger">{{ message }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="#" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/post.jpg' %}" alt="">
            <span class="d-none d-lg-block">OPIMS</span>
        </a>
    </div><!-- End Logo -->


    <nav class="header-nav ms-auto pe-3">
        <a href="{% url 'account:login' %}" class="btn  btn-outline-dark">Login</a>
        <a href="{% url 'account:register' 'customer' %}" class="btn  btn-outline-success" title="For Clients use only.">Register</a>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Wel-Come Page</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'post:index-view' %}">Home</a></li>
                <li class="breadcrumb-item active">{% block breadcrumb %} {% endblock %}</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        {% block middle %}

        {% endblock %}
    </section>
<script>
    function post_none(){
        setTimeout( function (){
            var cm = document.getElementsByClassName('custom-modal')[0];
            cm.classList.add('post_none');
        }, 2000);
    }
</script>
</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Online Ethiopian Postal System.</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>


</body>

</html>

templates/post/login.html
{% extends 'post/index_base.html' %}

{% block title %}
    Login
{% endblock %}

{% block breadcrumb %}
    login
{% endblock %}

{% block middle %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="pt-4 pb-2">
                        <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                        <p class="text-center small">Enter your username & password to login</p>
                    </div>
                    {% if revoke == "email" %}
                        <form method="post" action="" class="row g-3 needs-validation" novalidate>
                            {% csrf_token %}
                            <div class="col-12">
                                <label for="yourUsername" class="form-label">Email</label>
                                <div class="input-group has-validation">
                                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                                    <input type="email" name="email" class="form-control" id="yourUsername"
                                           placeholder="please enter your email" required>
                                    <div class="invalid-feedback">Your email is used to send a code.</div>
                                </div>
                            </div>

                            <div class="col-12">
                                <button class="btn btn-primary w-100" name="email_field" type="submit">Submit</button>
                            </div>
                            <div class="col-12">
                                <p class="small mb-0">Don't have account? <a
                                        href="{% url 'account:register' 'customer' %}">Create
                                    an account</a></p>
                            </div>
                        </form>
                    {% elif revoke == "code" %}
                        <form method="post" action="" class="row g-3 needs-validation" novalidate>
                            {% csrf_token %}
                            <div class="col-12">
                                <label for="yourUsername" class="form-label">Code</label>
                                <div class="input-group has-validation">
                                    <input type="text" name="codechar" class="form-control" id="yourUsername"
                                           placeholder="Enter the code you received" required>
                                    <div class="invalid-feedback">Check your email and finish the process.</div>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100" name="code" type="submit">Revoke</button>
                            </div>
                            <div class="col-12">
                                <p class="small mb-0">Don't have account? <a
                                        href="{% url 'account:register' 'customer' %}">Create
                                    an account</a></p>
                            </div>
                        </form>
                    {% elif revoke == "password" %}
                        <div class="">
                            <form method="post" action="{% url 'account:update_password_forgot' id %}">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <div class="col-md-12 mb-3">
                                        <input name="new_password" type="password" class="form-control"
                                               placeholder="New Password" required>
                                    </div>

                                    <div class="col-md-12 col-lg-12 mb-3">
                                        <input name="renew_password" type="password" class="form-control"
                                               placeholder="Re-enter New Password" required>
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" name="password_update" class="btn btn-primary">Change
                                        Password
                                    </button>
                                </div>
                            </form>

                        </div>
                    {% else %}
                        <form method="post" action="" class="row g-3 needs-validation" novalidate>
                            {% csrf_token %}
                            <div class="col-12">
                                <label for="yourUsername" class="form-label">Email</label>
                                <div class="input-group has-validation">
                                    <span class="input-group-text" id="inputGroupPrepend">@</span>
                                    <input type="email" name="email" class="form-control" id="yourUsername" required>
                                    <div class="invalid-feedback">Please enter your username.</div>
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="yourPassword" class="form-label">Password</label>
                                <input type="password" name="password" class="form-control" id="yourPassword" required>
                                <div class="invalid-feedback">Please enter your password!</div>
                            </div>

                            <div class="col-12">
                                <p class="small mb-0"><a href="{% url 'account:revoke-new-password' %}?revoke=true">I
                                    forgot my password.</a></p>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100" name="login" type="submit">Login</button>
                            </div>
                            <div class="col-12">
                                <p class="small mb-0">Don't have account? <a
                                        href="{% url 'account:register' 'customer' %}">Create
                                    an account</a></p>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/post/main_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} {% endblock %}-Dashboard | Online Ethiopian Post Office</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/post.jpg' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body onload="post_none()">
{# start of pop up message #}
<div class="page-wrapper ">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS or message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                <div class="custom-modal">
                    <div class="succes succes-animation icon-top"><i class="bi bi-check2"></i></div>

                    <div class="content">
                        <p class="message-type text-center small text-success">{{ message }}</p>
                    </div>
                </div>
            {% else %}
                <div class="custom-modal">
                    <div class="danger danger-animation icon-top"><i class="bi bi-x-lg"></i></div>
                    <div class="content">
                        <p class="message-type text-danger">{{ message }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{# end of pop up message #}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="#" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/post.jpg' %}" alt="">
            <span class="d-none d-lg-block">OPIMS</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    {% if notify|length != 0 %}
                        <span class="badge bg-primary badge-number">{{ notify|length }}</span>
                    {% endif %}
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have {{ notify|length }} new notifications
                        {% if notify|length != 0 %}
                            <a href="{% url 'post:all-or-one-to-seen' 'none' %}"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        {% endif %}
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    {% for post in notify %}
                        <li class="notification-item">
                            <i class="bi bi-info-circle text-primary"></i>
                            <div>
                                <h4>
                                    {% if post.is_sender_member %}
                                        From: {{ post.sender.first_name|title }} {{ post.sender.middle_name|title }}
                                    {% else %}
                                        From: {{ post.sender_full_name }}
                                    {% endif %}
                                </h4>
                                <p>Come up with your id and take your post <b>@Post Office</b> or call
                                    +25191102034565 </p>
                                <p>{{ post.date_send|timesince }} ago. <a href="{% url 'post:all-or-one-to-seen' post.id %}" class="font-monospace text-xl-right bg-info">Ok, i got.</a></p>
                            </div>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    {% endfor %}
                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->


            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.first_name|title }}. {{ user.middle_name|first|capfirst }}</span>
                </a><!-- End Profile Image Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ user.first_name|title }} {{ user.middle_name|title }}</h6>
                        <span>{% if user.is_costumer == True %}
                            Costumer
                        {% elif user.is_admin == True %}
                            Admin
                        {% elif user.is_postman == True %}
                            Post Man
                        {% elif user.is_counter == True %}
                            Counter
                        {% endif %} </span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="/{% if role == 'costumer' %}user{% else %}{{ role }}{% endif %}/?pages=profile">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center"
                           href="/{% if role == 'costumer' %}user{% else %}{{ role }}{% endif %}/?pages=profile">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'account:logout' %}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->
</header>
<aside id="sidebar" class="sidebar">
    {% block aside %}

    {% endblock %}
</aside>
<main id="main" class="main">

    <div class="pagetitle">
        <h1>{% block header %} {% endblock %}</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item">{% block middle_breadcrumb %}{% endblock %}</li>
                <li class="breadcrumb-item active">{% block active_breadcrumb %}{% endblock %}</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        {% block middle %}{% endblock %}
    </section>
    <script>
        function post_none() {
            setTimeout(function () {
                var cm = document.getElementsByClassName('custom-modal')[0];
                cm.classList.add('post_none');
            }, 2000);
        }
    </script>
</main><!-- End #main -->

<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Online Ethiopian Postal System.</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/post/register.html
{% extends 'post/index_base.html' %}

{% block title %}
    Register
{% endblock %}

{% block breadcrumb %}
    register
{% endblock %}

{% block middle %}
    <div class="row justify-content-center">
        <div class="col-md-6 d-flex flex-column align-items-center justify-content-center">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="pt-4 pb-2">
                        <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                        <p class="text-center small">Enter your personal details to create account</p>

                    </div>
                    <form method="post" action="" class="row g-3 needs-validation" novalidate>
                        {% csrf_token %}
                        {% for form in rf_form %}
                            <div class="col-12">
                                <label for="{{ form.id_for_label }}" class="form-label">{{ form.label }}</label>
                                {{ form }}
                                {% if forloop.counter0 == 4 %}
                                    <div class="invalid-feedback">Make sure your password is more than 4 char.</div>
                                {% else %}
                                    <div class="invalid-feedback">Please, enter your {{ form.label }}!</div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-12">
                            <button class="btn btn-primary w-100" type="submit">Create Account</button>
                        </div>
                        <div class="col-12">
                            <p class="small mb-0">I had account ! <a href="{% url 'account:login' %}">Login to
                                an account</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/post/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report</title>
</head>
<style>
    @page {
        size: {{ pagesize|default:"A4" }};
        margin: 2.5cm 1.5cm 1.5cm 1.5cm;
    }


</style>
<body>
<h1>Ethiopian Post Office Report</h1>
<table class="table" style="border-collapse: collapse">
    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">Sender</th>
        <th scope="col">S. phone</th>
        <th scope="col">S. Address</th>
        <th scope="col">Receiver</th>
        <th scope="col">R. phone</th>
        <th scope="col">S. Address</th>
    </tr>
    </thead>
    <tbody>
    {% for post in posts %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            {% if post.is_sender_member %}
                <td>{{ post.sender.first_name|title }} {{ post.sender.middle_name|title }}</td>
                <td>{{ post.sender.phone }}</td>
                <td>{{ post.sender.address }}</td>
            {% else %}
                <td>{{ post.sender_full_name }}</td>
                <td>{{ post.sender_phone }}</td>
                <td>{{ post.sender_address }}</td>
            {% endif %}
            {% if post.is_receiver_member %}
                <td>{{ post.receiver.first_name|title }} {{ post.sender.middle_name|title }}</td>
                <td>{{ post.receiver.phone }}</td>
                <td>{{ post.receiver.address }}</td>
            {% else %}
                <td>{{ post.rec_full_name }}</td>
                <td>{{ post.rec_phone }}</td>
                <td>{{ post.rec_address }}</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>